### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'resources/geckodriver'

### ISSUE THREAD

**Issue by alxhoff** [munober/webscrapper#10]
**Describe the bug**
Only realizes the geckodriver is missing a while into execution

**To Reproduce**
Run without geckodriver in PATH

**Expected behavior**
Throw an error at the beginning of execution and/or download geckodriver automatically

**Comment by munober** [comment]
didn't realize that would happen, nice!

**Comment by alxhoff** [comment]
This isn't fixed. Somehow after my fix you still hav

```
web_driver = webdriver.Firefox(executable_path=DRIVER_PATH)
``` 
This throws an error and void the use of the automatic geckodriver resolution provided by `geckodriver_autoinstaller`.

Your commit c265c59590fa03df6129f0fc94666e6d0786bb0f undid ,my fix as I image you did not pull the changes after merging the PR in the web interface.

**Comment by munober** [comment]
Okay so I didn't properly explain what I did, sorry. I did pull everything after merging in the web interface, I just had to comment out your edit at the last minute to get this stuff to work on my own setup. Let me explain. 
On windows using pycharm, where I built 99% of the project, I get an error when running the gecko autoinstaller, and if I understand correctly, it's related to them appending tar.gz instead of .zip to the end of the github link from where they pull the driver off so it goes to github/.../win32.tar.gz which doesnt exist, delivers a 404 and the whole script crashes. With that being so, I just left it using the locally downloaded driver which works on windows, and as it is on the master branch now. I meant to add  an if os == "nt" and elif linux using the autoinstaller, but forgot to before committing.

Now on manjaro, where I did all my Linux testing, if I run the code using your fix, it returns a permission error, and running everything with sudo spits out yet another error. I'm not sure why. 

What this means is I currently can only get this running on my side with the code from master. What I did is created another branch called autoinstaller, where your fix is integrated, but the code from which doesn't work on either windows or manjaro for me. Could you check it on your system and tell me if it works for you like that? Does it download the driver properly?

On master, I have also added the linux geckodriver to the git repo under /resources, so even without the autoinstaller, it will work on linux too, please check this on your system, it works on my manjaro.

**Comment by munober** [comment]
I think I found a good compromise now, it will come on the next commit on master, I included both your fix and kept the locally saved geckodriver file around for windows/my manjaro which both can't successfully run geckodriver_autoinstaller. I hope it works on your system too.

They seem to be working on the .tar.gz vs .zip error: https://github.com/yeongbin-jo/python-geckodriver-autoinstaller/issues/2

**Comment by alxhoff** [comment]
Seems to work. I would also make face filtering the default. Maybe -f can disable it. Our default use should have as few options as possible.

**Comment by alxhoff** [comment]
> I think I found a good compromise now, it will come on the next commit on master, I included both your fix and kept the locally saved geckodriver file around for windows/my manjaro which both can't successfully run geckodriver_autoinstaller. I hope it works on your system too.
> 
> They seem to be working on the .tar.gz vs .zip error: [yeongbin-jo/python-geckodriver-autoinstaller#2](https://github.com/yeongbin-jo/python-geckodriver-autoinstaller/issues/2)

I have fixed up it up in a new PR
